include = [
  "mise/config.toml"
]

[formatting]
align_entries = true
allowed_blank_lines = 1
array_auto_collapse = true
array_auto_expand = true
column_width = 80
compact_arrays = true
indent_string = "    "
reorder_keys = false

[[rule]]
include = ["mise/config.toml"]
keys = ["settings", "tools"]
formatting = { reorder_keys = true }
